@TaskManager_Api_HostAddress = http://localhost:5284

POST {{TaskManager_Api_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "Finish GitHub project",
  "description": "Add POST endpoint",
  "isCompleted": false
}